title: PsycheYouth!
logo: "images/logo.png" # You can add own logo image.
description: Idealistic and reckless
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://imamnrchls.xyz" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Imam Nurcholis
  bio: Hi, my name is Imam Nurcholis. I like reading a book all day long, being free and enjoy every moment.

# Contact links
twitter: https://twitter.com/imamnrchls
facebook: https://facebook.com/imemnur
dribbble: https://dribbble.com/imamnrchls
instagram: https://instagram.com/imamnrchls
# pinterest: https://pinterest.com/ # Add your Pinterest handle
email: imamnrchls@outlook.com

# Hero Section
hero: false # To enable the section hero, use the value true. To turn off use the value false.
hero-title: PsycheYouth! # Add your hero title
hero-subtitle: Idealistic and reckless # Add your hero subtitle
hero-image: images/01.jpg # Add background image in section hero

# Footer
footer-image: images/15.jpg # Add background image in footer

# Comment Section (Disqus)
disqus-identifier: imamnrchls,github.io

# Google Analytics
google-analytics: "UA-142487742-2" # Add your identifier. For example UA-99631805-1.

# Newsletter
# mailchimp: "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
